### ISSUE TITLE
Support for negative numbers

### ISSUE THREAD

**Issue by phillco** [wenkokke/talonfmt#17]
```
notification.talon
Parse error on line 9 between column 32 and 33:
	user.notification_show_actions(-1)

```

I believe these are valid syntax.

**Comment by wenkokke** [comment]
Thanks! This is a tree-sitter-talon bug, though.

**Comment by wenkokke** [comment]
@philco Fixed in tree-sitter-talon. Should be fixed once I upgrade the dependencies.

**Comment by phillco** [comment]
Thanks! I'll file future bugs in that project. :)
