### ISSUE TITLE
`1.8.0` release tag isn't on the default branch

### ISSUE THREAD

**Issue by phillco** [wenkokke/talonfmt#25]
Right now, `pre-commit autoupdate` thinks 1.7.4 is the latest version and will actually downgrade installations of 1.8.0: https://github.com/knausj85/knausj_talon/pull/991

I looked up how `pre-commit` determines the latest version, and it says this:

> By default, this will bring the hooks to the latest tag on the default branch.

I think the problem is that the `1.8.0` tag isn't on the default branch (`dev`), so that's why it's not considered as the latest release. `1.7.4` is.

<img width="1460" alt="Screen Shot 2022-10-03 at 2 41 44 PM" src="https://user-images.githubusercontent.com/536668/193691198-9a5cd60a-2991-4b5f-beef-73fac4fb5cb7.png">

Force pushing `1.8.0` to a commit on `dev`, or creating a new `1.8.1` tag that is, should resolve the problem.

You can reproduce by cd'ing into knausj and running `pre-commit autoupdate`.

**Comment by wenkokke** [comment]
Wild, thanks!

**Comment by phillco** [comment]
Mind taking a stab at pushing a new tag? pre-commit.ci is still trying to downgrade 1.8.0 installations: https://github.com/phillco/talon-axkit/pull/40. I would open a pull request, except you can't open a pull request for a tag :)

**Comment by wenkokke** [comment]
Hopefully fixed now?

**Comment by phillco** [comment]
Yup! Thanks!

```
$ pre-commit autoupdate
Updating https://github.com/pre-commit/pre-commit-hooks ... already up to date.
Updating https://github.com/pre-commit/mirrors-prettier ... [INFO] Initializing environment for https://github.com/pre-commit/mirrors-prettier.
updating v3.0.0-alpha.0 -> v3.0.0-alpha.2.
Updating https://github.com/ikamensh/flynt/ ... already up to date.
Updating https://github.com/pycqa/isort ... already up to date.
Updating https://github.com/psf/black ... [INFO] Initializing environment for https://github.com/psf/black.
updating 22.8.0 -> 22.10.0.
Updating https://github.com/Lucas-C/pre-commit-hooks ... already up to date.
Updating https://github.com/wenkokke/talonfmt ... [INFO] Initializing environment for https://github.com/wenkokke/talonfmt.
updating 1.8.0 -> 1.8.1.
```
