### ISSUE TITLE
VSCode formatting plugin

### ISSUE THREAD

**Issue by pokey** [wenkokke/talonfmt#26]
It would be nice to have support for automatically applying `talonfmt` on save.  Maybe that should go into the [vscode-talonscript extension](https://marketplace.visualstudio.com/items?itemName=mrob95.vscode-talonscript)?  cc/ @mrob95

Maybe we should transfer this issue over to https://github.com/mrob95/vscode-TalonScript/ if it seems like a good fit

**Comment by wenkokke** [comment]
Sure. I have a repository with the skeleton taken from the `cabal-fmt` plugin: <wenkokke/talonfmt-vscode>

**Comment by mirober** [comment]
Sure, I would be happy for it to be merged into the syntax highlighting extension if that is the best approach. I don't want to slow down the feedback loop by being slow to publish new versions though, so I wonder if it would be worth publishing a separate extension to iterate quickly and get it to a stable state before consolidating into one extension?

**Comment by wenkokke** [comment]
@mrob95 Is VSCode happy with two plugins defining a language?

**Comment by pokey** [comment]
I'm sure that's fine, and if it ends up being a problem we can just make @mrob95's extension a dependency of the formatter extension, as I'd imagine people will want syntax highlighting if they want a formatter

**Comment by pokey** [comment]
Actually looks like VSCode just published a [new template](https://code.visualstudio.com/api/advanced-topics/python-extension-template) for developing extensions that use a Python module to format documents.  By default they assume you'll be formatting Python documents, but I think that should be trivial to change.  Looks like it should make things pretty easy

**Comment by wenkokke** [comment]
Ohh, nice!

**Comment by pokey** [comment]
And the cool thing is it's an lsp so should be able to adapt it to other editors without too much effort

**Comment by wenkokke** [comment]
It does depend on the Python extension, not sure if that'd be an objection?

Might also mean that we'll run into some issues where it really only works if there's Python files active, even if we change this extension's `onLanguage`?

**Comment by pokey** [comment]
Do you know if that requirement is necessary? What does it use the Python extension for?

**Comment by wenkokke** [comment]
Presumably, running Python?

**Comment by wenkokke** [comment]
@pokey Fixed, see:

- [wenkokke/talonfmt-vscode](https://github.com/wenkokke/talonfmt-vscode)
- [Talon Formatter Extension](https://marketplace.visualstudio.com/items?itemName=wenkokke.talonfmt-vscode)

**Comment by pokey** [comment]
Epic! Will have a look.

Should also be useful scaffolding to build a formatter for tree-sitter's query language, as there is already a tree-sitter grammar for that
