### ISSUE TITLE
Support configuration options

### ISSUE THREAD

**Issue by pokey** [wenkokke/talonfmt#57]
It would be useful to be able to control configuration options to talonfmt, specifically `--max-line-width`.  A few options, all of which would be useful:

- `talonfmt` could read from something standard like `pyproject.toml`
- `talonfmt` could read from some global user configuration
- ability to specify options in config for vscode extension

**Comment by wenkokke** [comment]
I'd say either option three or a `.talonfmt.toml` file in the directory? Or simply respect editorconfig?

**Comment by pokey** [comment]
Yeah editorconfig sounds good to me

**Comment by wenkokke** [comment]
Supported in HEAD of talonfmt, release pending.

**Comment by pokey** [comment]
Awesome!

**Comment by wenkokke** [comment]
Fixed in 1.9.0.

**Comment by pokey** [comment]
(fixed in https://github.com/wenkokke/talonfmt/commit/de8d338fb71857967e43513501abbd261a5f5e94 I believe)
