### ISSUE TITLE
Running formatter inserts spurious text

### ISSUE THREAD

**Issue by pokey** [wenkokke/talonfmt#60]
The `.editorconfig` support (https://github.com/wenkokke/talonfmt/issues/57 / https://github.com/wenkokke/talonfmt/commit/de8d338fb71857967e43513501abbd261a5f5e94) seems to work great on `talonfmt`, but when I try to run the formatter from VSCode, the extension inserts the following at the top of the file I'm trying to format:

```
Got max_line_width=80 from .editorconfig
```

It does seem to be performing the formatting on the rest of the document, though

**Comment by wenkokke** [comment]
Oh, shit, I left in the logging statement.

**Comment by wenkokke** [comment]
Fixed in HEAD

**Comment by wenkokke** [comment]
Fixed in 1.9.1

**Comment by pokey** [comment]
Awesome thanks. Would be great to have a basic sanity test for things like that, as I'm planning to have this run every time I save 😅

**Comment by wenkokke** [comment]
> Awesome thanks. Would be great to have a basic sanity test for things like that, as I'm planning to have this run every time I save 😅

Apologies, I don't have the bandwidth at the moment to add the editorconfig tests, since they're not straightforward :/

**Comment by pokey** [comment]
But this issue appears even without any editorconfig present.

I just ran it on 1.9.0 without editorconfig:

```bash
➜ talonfmt apps/vscode/vscode.talon 2>/dev/null | head
Got max_line_width=None from .editorconfig
Got indent_size=None from .editorconfig
#custom vscode commands go here
app: vscode
-
tag(): user.find_and_replace
tag(): user.line_commands
tag(): user.multiple_cursors
tag(): user.snippets
tag(): user.splits
```

**Comment by wenkokke** [comment]
Yes, but it’s logging code I inserted when implementing the editorconfig support.

I guess your point is to also implant tests for using talonfmt as a pipe.

**Comment by pokey** [comment]
If the vscode extension operates by using talonfmt as a pipe, then yes, I think that kind of test would be great to have, and presumably not too painful to implement?
